### PR TITLE
Cow-ify token repository

### PR DESCRIPTION
**Pull request by nlordell**
This PR changes the package name from `@gnosis.pm/cow-token` to `@cowprotocol/token` and adjusts the publishing workflow for publishing directly from GitHub.

GitHub Actions workflow changes base on: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-using-yarn

### Test Plan

Deploy with GitHub action 🎉.

### CODE REVIEW

**Review by fedgiac — COMMENTED** [review]
Looks good!

Please also change the package name in the readme here: https://github.com/cowprotocol/token#use-the-code-in-another-project=.

**Comment by nlordell** [comment]
Fixed!

**Comment by nlordell** [comment]
Also, to double check I didn't miss anything else:
```
% rg -uuu '@gnosis\.pm' | wc -l
      30
% rg -uuu '@gnosis\.pm/safe' | wc -l
      30
```

meaning that all uses of `@gnosis.pm/` NPM org packages are for `safe-*` packages (contracts and deployments).

**Review by fedgiac — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
